enve::polynom
typedef std::shared_ptr<polynom const> enve::polynom::ptr
Pointer to polynom object.
typedef std::vector<polynom::ptr> enve::polynom::vecptr
Vector of pointers to polynom objects.
vecN enve::polynom::m_coeffs
Polynomial regression coefficients.
Referenced by copy, fit, isApprox, print, surfaceDerivative, surfaceRadius.
real enve::shape::m_maxR
Maximum surface maximum radius (m)
Referenced by enve::shape::copy, enve::shape::isApprox, enve::shape::print, enve::shape::shape, enve::shape::surfaceMaxRadius.
real enve::shape::m_minY
Minimum surface bound on y axis (m)
Referenced by enve::shape::checkWidthBound, enve::shape::copy, enve::shape::isApprox, enve::shape::print, enve::shape::shape, enve::shape::surfaceMaxWidth, enve::shape::surfaceWidth, enve::shape::surfaceWidthLowerBound.
real enve::shape::m_maxY
Maximum surface bound on y axis (m)
Referenced by enve::shape::checkWidthBound, enve::shape::copy, enve::shape::isApprox, enve::shape::print, enve::shape::shape, enve::shape::surfaceMaxWidth, enve::shape::surfaceWidth, enve::shape::surfaceWidthUpperBound.
enve::polynom::~polynom(void)
Polynom class destructor.
enve::polynom::polynom(polynom const &)=default
Polynom copy constructor.
enve::polynom::polynom(polynom &&)=default
Polynom move constructor.
enve::polynom::polynom(void)
Polynom class constructor.
enve::polynom::polynom(vecN coeffs, real maxR, real minY, real maxY)
Polynomial regression coefficients
enve::polynom::polynom(vecN const &dataR, vecN const &dataY, size_t order, real tolerance=EPSILON_MEDIUM)
Vector of radius data (m)
void enve::polynom::copy(polynom const &polynom_in)
Polynom object to be copied
bool enve::polynom::isApprox(polynom const &polynom_in, real tolerance=EPSILON_LOW) const
Input object
real enve::polynom::surfaceRadius(real y) const override
Coordinate of y axis
real enve::polynom::surfaceDerivative(real y, real tolerance=EPSILON_MEDIUM) const override
Coordinate of y axis
Referenced by surfaceAngle.
real enve::polynom::surfaceAngle(real y, real tolerance=EPSILON_MEDIUM) const override
Coordinate of y axis
void enve::polynom::print(out_stream &os) const
Output stream type
void enve::polynom::fit(vecN dataR, vecN dataY, size_t order, real tolerance=EPSILON_MEDIUM)
Vector of radius data (m)
Referenced by polynom.
void enve::shape::copy(shape const &shape_in)
Shape object to be copied
Referenced by enve::hyperellipse::copy, enve::points::copy, copy.
bool enve::shape::isApprox(shape const &shape_in, real tolerance=EPSILON_LOW) const
Shape object
Referenced by enve::hyperellipse::isApprox, enve::points::isApprox, isApprox.
real const & enve::shape::surfaceMaxRadius(void) const
Get surface maximum radius const reference (m)
Referenced by enve::hyperellipse::updateBounds.
real & enve::shape::surfaceMaxRadius(void)
Get surface maximum radius on reference (m)
real enve::shape::surfaceMaxWidth(void) const
Get surface maximum width on y axis (m)
real const & enve::shape::surfaceWidthLowerBound(void) const
Get surface minimum width const reference (m)
Referenced by enve::hyperellipse::updateBounds.
real & enve::shape::surfaceWidthLowerBound(void)
Get surface minimum width on reference (m)
real const & enve::shape::surfaceWidthUpperBound(void) const
Get surface maximum width const reference (m)
Referenced by enve::hyperellipse::updateBounds.
real & enve::shape::surfaceWidthUpperBound(void)
Get surface maximum width on reference (m)
real enve::shape::surfaceWidth(void) const
Get surface width (m)
bool enve::shape::checkWidthBound(real y) const
Coordinate of y axis
Referenced by enve::points::lowerBound, enve::hyperellipse::surfaceDerivative, enve::points::surfaceDerivative, surfaceDerivative, enve::hyperellipse::surfaceRadius, enve::points::surfaceRadius, surfaceRadius, enve::points::upperBound.