enve::shell
typedef std::shared_ptr<shell const> enve::shell::ptr
Pointer to shell object.
typedef std::vector<shell::ptr> enve::shell::vecptr
Vector of pointers to shell objects.
std::shared_ptr<shape> enve::shell::m_shape
Shell shape.
Referenced by checkWidthBound, contactDepthMesh, contactDepthRib, print, reset, samplingCross, surfaceAngle, surfaceDerivative, surfaceMaxRadius, surfaceMaxWidth, surfaceRadius, surfaceWidth, surfaceWidthLowerBound, surfaceWidthUpperBound, updateBBox.
std::vector<rib> enve::shell::m_ribs
Shell ribs vector.
Referenced by contactDepthMesh, contactDepthRib, envelopLine, envelopPlane, envelopSingleTriangle, envelopTriangle, oversample, print, projectContactPointOnFlat, projectContactPointOnMesh, relativeAngles, reset, ribCenter, ribRadius, ribWidth, size.
affine enve::shell::m_affine
Shell reference frame (ISO)
Referenced by contactDepthMesh, contactDepthRib, envelopPlane, envelopTriangle, eulerAngles, linear, print, projectContactPointOnFlat, projectContactPointOnMesh, rotate, rotation, samplingCross, setup, shell, transform, transformation, translate, translation, updateBBox, x, y, z.
std::shared_ptr<aabb> enve::shell::m_bbox
Shell bounding aabb (must be transformed in the mesh reference frame before intersection!)
Referenced by bbox, setup, updateBBox.
std::vector<point> enve::shell::m_pointRib
Contact points vector on mesh (projected on rib plane)
Referenced by contactDepthRib, contactPointRib, contactPointRibAffine, envelopLine, envelopPlane, envelopSingleTriangle, envelopTriangle, oversample, reset.
std::vector<point> enve::shell::m_pointMesh
Contact points vector on mesh (projected on the mesh)
Referenced by contactDepthMesh, contactPointMesh, contactPointMeshAffine, envelopLine, envelopPlane, envelopSingleTriangle, envelopTriangle, oversample, reset.
std::vector<vec3> enve::shell::m_normal
Contact normal vectors vector.
Referenced by contactNormal, contactPointMeshAffine, contactPointRibAffine, envelopLine, envelopPlane, envelopSingleTriangle, envelopTriangle, oversample, reset.
vecN enve::shell::m_friction
Contact friction.
Referenced by contactFriction, envelopLine, envelopPlane, envelopSingleTriangle, envelopTriangle, oversample, reset.
vecN enve::shell::m_depth
Contact depth.
enve::shell::~shell(void)
Shell class destructor.
enve::shell::shell(shell const &)=delete
Shell copy constructor.
enve::shell::shell(shell const &&)=delete
Shell move constructor.
enve::shell::shell(size_t size, real r_x, real m_x, real r_y, real m_y, real l_y)
Input ribs number
enve::shell::shell(size_t size, vecN const &dataR, vecN const &dataY, size_t order, real tolerance=EPSILON_MEDIUM)
Input ribs number
enve::shell::shell(size_t size, vecN const &dataR, vecN const &dataY)
Input ribs number
enve::shell::shell(size_t size, hyperellipse const &hyperellipse_in)
Input ribs number
enve::shell::shell(size_t size, polynom const &polynom_in)
Input ribs number
void enve::shell::reset(size_t size)
Input ribs number
Referenced by shell.
size_t enve::shell::size(void) const
Get shell ribs number.
Referenced by contactDepthMesh, contactDepthRib, contactNormal, contactPointMesh, contactPointMeshAffine, contactPointRib, contactPointRibAffine, print, relativeAngles, reset, setup.
real enve::shell::surfaceMaxRadius(void) const
Get shell surface maximum radius (m)
real enve::shell::surfaceMaxWidth(void) const
Get shell surface maximum width on y axis (m)
real enve::shell::surfaceWidthLowerBound(void) const
Get shell surface minimum width (m)
real enve::shell::surfaceWidthUpperBound(void) const
Get shell surface maximum width (m)
real enve::shell::surfaceWidth(void) const
Get shell surface width (m)
bool enve::shell::checkWidthBound(real y) const
Coordinate of y axis
real enve::shell::surfaceRadius(real y) const
Coordinate of y axis
real enve::shell::surfaceDerivative(real y, real tolerance=EPSILON_MEDIUM) const
Coordinate of y axis
real enve::shell::surfaceAngle(real y, real tolerance=EPSILON_MEDIUM) const
Coordinate of y axis
real enve::shell::ribRadius(size_t i) const
Input index
point enve::shell::ribCenter(size_t i) const
Input index
real enve::shell::ribWidth(size_t i) const
Input index
Referenced by reset.
void enve::shell::translate(vec3 const &vector_in)
Translation vector
vec3 enve::shell::translation(void) const
Returns shell translation vector.
void enve::shell::rotate(real angle, vec3 const &axis)
Input angle (rad)
void enve::shell::rotate(real angle, std::string const &axis)
Input angle (rad)
mat3 enve::shell::rotation(void) const
Returns shell rotation matrix.
Referenced by envelopPlane, envelopTriangle, relativeAngles.
mat3 enve::shell::linear(void) const
Returns shell linear matrix (rotation + scaling + shearing)
void enve::shell::transform(affine const &matrix_in)
Input 4x4 affine transformation matrix
Set 4x4 affine transformation matrix Warning: Rotation matrix must be orthonormal!
void enve::shell::transform(mat4 const &matrix_in)
Input 4x4 affine transformation matrix
Set 4x4 affine transformation matrix Warning: Rotation matrix must be orthonormal!
affine const & enve::shell::transformation(void) const
Get 4x4 affine transformation matrix.
vec3 enve::shell::x(void) const
Get x vector.
vec3 enve::shell::y(void) const
Get y vector.
Referenced by contactPointMeshAffine, contactPointRibAffine.
vec3 enve::shell::z(void) const
Get z vector.
Referenced by envelopLine, envelopSingleTriangle, samplingPoint.
void enve::shell::eulerAngles(vec3 &angles) const
Frame Euler angles
Get current Euler angles (rad) WARNING: Rotation sequence ZXY!
Referenced by print.
std::shared_ptr< aabb > enve::shell::bbox(void) const
Get shell bonding aabb as object pointer vector.
void enve::shell::updateBBox(void)
Update shell bonding aabb.
Referenced by reset, setup, shell.
void enve::shell::relativeAngles(vec3 &angles) const
Relative angles vector (rad)
Get shell relative angles (rad) WARNING: Rotation sequence ZXY!
Referenced by print, relativeAngles.
void enve::shell::relativeAngles(size_t i, vec3 &angles) const
Input i-th index
Get shell relative angles for the i-th rib (rad) WARNING: Rotation sequence ZXY!
void enve::shell::relativeAngles(std::vector< vec3 > &angles) const
Relative angles vector (rad)
Get shell relative angles as vector (rad) WARNING: Rotation sequence ZXY!
void enve::shell::contactDepthRib(real &depth, real &depth_dot, real depth_old, real time_step) const
Depth at center point [m/s]
Referenced by contactDepthRib, print.
void enve::shell::contactDepthRib(size_t i, real &depth, real &depth_dot, real depth_old, real time_step) const
Input i-th index
void enve::shell::contactDepthRib(vecN &depth, vecN &depth_dot, vecN const &depth_old, real time_step) const
Depth matrix [m/s]
void enve::shell::contactDepthMesh(real &depth, real &depth_dot, real depth_old, real time_step) const
Depth at center point [m/s]
Referenced by contactDepthMesh, print.
void enve::shell::contactDepthMesh(size_t i, real &depth, real &depth_dot, real depth_old, real time_step) const
Input i-th index
void enve::shell::contactDepthMesh(vecN &depth, vecN &depth_dot, vecN const &depth_old, real time_step) const
Depth matrix [m/s]
void enve::shell::contactNormal(vec3 &normal) const
Contact point normal direction
Referenced by contactPointMeshAffine, contactPointRibAffine, print.
void enve::shell::contactNormal(size_t i, vec3 &normal) const
Input i-th index
void enve::shell::contactNormal(std::vector< vec3 > &normal) const
Contact point normal direction vector
void enve::shell::contactPointRib(point &point) const
Contact point
Referenced by contactDepthRib, contactPointRibAffine, print.
void enve::shell::contactPointRib(size_t i, point &point) const
Input i-th index
void enve::shell::contactPointRib(std::vector< point > &point) const
Contact points vector
void enve::shell::contactPointMesh(point &point) const
Contact point
Referenced by contactDepthMesh, contactPointMeshAffine, print.
void enve::shell::contactPointMesh(size_t i, point &point) const
Input i-th index
void enve::shell::contactPointMesh(std::vector< point > &point) const
Contact points vector
void enve::shell::contactFriction(real &friction) const
Contact friction coefficient
Referenced by print.
void enve::shell::contactFriction(size_t i, real &friction) const
Input i-th index
void enve::shell::contactFriction(vecN &friction) const
Contact friction coefficients vector
void enve::shell::contactPointRibAffine(affine &point_affine) const
Contact point affine transformation matrix
Referenced by contactPointRibAffine, print, relativeAngles.
void enve::shell::contactPointRibAffine(size_t i, affine &point_affine) const
Input i-th index
void enve::shell::contactPointRibAffine(std::vector< affine > &point_affine) const
Contact point affine transformation matrices vector
void enve::shell::contactPointMeshAffine(affine &point_affine) const
Contact point affine transformation matrix
Referenced by contactPointMeshAffine, print.
void enve::shell::contactPointMeshAffine(size_t i, affine &point_affine) const
Input i-th index
void enve::shell::contactPointMeshAffine(std::vector< affine > &point_affine) const
Contact point affine transformation matrices vector
bool enve::shell::setup(ground::mesh const &ground, affine const &matrix, size_t threshold, std::string const method)
ENVE mesh object (ground)
bool enve::shell::setup(ground::flat const &ground, affine const &matrix)
ENVE flat object (ground)
void enve::shell::print(out_stream &os) const
Output stream type
void enve::shell::oversample(size_t o, size_t a, size_t b)
Rib index to be filled by oversampled data
Referenced by setup.
bool enve::shell::samplingSingleTriangle(triangleground::vecptr const &triangles_vec, point const &origin, vec3 const &direction, point &point, vec3 &normal, real &friction) const
Triangles list (with only one element!)
Referenced by envelopSingleTriangle.
bool enve::shell::samplingPoint(triangleground::vecptr const &triangles_vec, point const &origin, vec3 const &direction, point &point, vec3 &normal, real &friction) const
Triangles list
Referenced by projectContactPointOnMesh, samplingCross.
bool enve::shell::samplingCross(triangleground::vecptr const &triangles_vec, point const &origin, vec3 const &direction, real delta_x, real delta_y, point &point, vec3 &normal, real &friction) const
Triangles list
Referenced by envelopLine.
bool enve::shell::envelopSingleTriangle(triangleground::vecptr const &triangles_vec, size_t i)
Triangles candidate list
Referenced by setup.
bool enve::shell::envelopLine(triangleground::vecptr const &triangles_vec, size_t i)
Triangles candidate list
Referenced by setup.
bool enve::shell::envelopTriangle(triangleground::vecptr const &triangles_vec, size_t i)
Triangles candidate list
Referenced by setup.
bool enve::shell::envelopPlane(ground::flat const &ground, size_t i)
Local flat ground object
Referenced by setup.
bool enve::shell::projectContactPointOnFlat(ground::flat const &ground, point const &point_rib, vec3 const &direction, size_t i, point &point_out) const
Referenced by envelopPlane.
bool enve::shell::projectContactPointOnMesh(triangleground::vecptr const &triangles, point const &point_rib, vec3 const &direction, size_t i, point &point_out) const
Referenced by envelopLine, envelopSingleTriangle, envelopTriangle.