enve::shape
typedef std::shared_ptr<shape const> enve::shape::ptr
Pointer to shape object.
typedef std::vector<shape::ptr> enve::shape::vecptr
Vector of pointers to shape objects.
real enve::shape::m_maxR
Maximum surface maximum radius (m)
Referenced by copy, isApprox, print, shape, surfaceMaxRadius.
real enve::shape::m_minY
Minimum surface bound on y axis (m)
Referenced by checkWidthBound, copy, isApprox, print, shape, surfaceMaxWidth, surfaceWidth, surfaceWidthLowerBound.
real enve::shape::m_maxY
Maximum surface bound on y axis (m)
Referenced by checkWidthBound, copy, isApprox, print, shape, surfaceMaxWidth, surfaceWidth, surfaceWidthUpperBound.
virtual enve::shape::~shape(void)
Shape class destructor.
enve::shape::shape(void)
Shape class constructor.
enve::shape::shape(real maxR, real minY, real maxY)
Maximum surface maximum radius (m)
enve::shape::shape(vecN const &dataR, vecN const &dataY)
Vector of radius data (m)
void enve::shape::copy(shape const &shape_in)
Shape object to be copied
Referenced by enve::hyperellipse::copy, enve::points::copy, enve::polynom::copy.
bool enve::shape::isApprox(shape const &shape_in, real tolerance=EPSILON_LOW) const
Shape object
Referenced by enve::hyperellipse::isApprox, enve::points::isApprox, enve::polynom::isApprox.
real const & enve::shape::surfaceMaxRadius(void) const
Get surface maximum radius const reference (m)
Referenced by enve::hyperellipse::updateBounds.
real & enve::shape::surfaceMaxRadius(void)
Get surface maximum radius on reference (m)
real enve::shape::surfaceMaxWidth(void) const
Get surface maximum width on y axis (m)
real const & enve::shape::surfaceWidthLowerBound(void) const
Get surface minimum width const reference (m)
Referenced by enve::hyperellipse::updateBounds.
real & enve::shape::surfaceWidthLowerBound(void)
Get surface minimum width on reference (m)
real const & enve::shape::surfaceWidthUpperBound(void) const
Get surface maximum width const reference (m)
Referenced by enve::hyperellipse::updateBounds.
real & enve::shape::surfaceWidthUpperBound(void)
Get surface maximum width on reference (m)
real enve::shape::surfaceWidth(void) const
Get surface width (m)
bool enve::shape::checkWidthBound(real y) const
Coordinate of y axis
Referenced by enve::points::lowerBound, enve::hyperellipse::surfaceDerivative, enve::points::surfaceDerivative, enve::polynom::surfaceDerivative, enve::hyperellipse::surfaceRadius, enve::points::surfaceRadius, enve::polynom::surfaceRadius, enve::points::upperBound.
virtual real enve::shape::surfaceRadius(real y) const =0
Coordinate of y axis
virtual real enve::shape::surfaceDerivative(real y, real tolerance=EPSILON_MEDIUM) const =0
Coordinate of y axis
virtual real enve::shape::surfaceAngle(real y, real tolerance=EPSILON_MEDIUM) const =0
Coordinate of y axis
void enve::shape::print(out_stream &os) const
Output stream type
Referenced by enve::hyperellipse::print, enve::points::print, enve::polynom::print.