enve::triangleground
typedef std::shared_ptr<triangleground const> enve::triangleground::ptr
Pointer to object.
typedef std::vector<triangleground::ptr> enve::triangleground::vecptr
Vector of pointers to objects.
integer enve::triangleground::m_id
ID (-)
Referenced by id, print, updateBbox.
real enve::triangleground::m_friction
Friction coefficient scaling factor (-)
Referenced by copy, friction, isApprox, print.
vec3 enve::triangleground::m_normal
Unit normal (-)
Referenced by copy, normal, updateNormal.
aabb enve::triangleground::m_bbox
Axis-aligned bounding box (m)
Referenced by bbox, copy, updateBbox.
enve::triangleground::triangleground(triangleground const &)=delete
Triangleground copy constructor.
enve::triangleground::triangleground(triangleground &&)=delete
Triangleground move constructor.
triangleground & enve::triangleground::operator=(const triangleground &)=delete
Triangleground assignment operator
triangleground & enve::triangleground::operator=(triangleground &&)=delete
Triangleground move assignment operator
enve::triangleground::~triangleground(void) override=default
Triangleground class destructor.
enve::triangleground::triangleground(void)
Triangleground class constructor.
enve::triangleground::triangleground(integer id, real friction, real vertex_0_x, real vertex_0_y, real vertex_0_z, real vertex_1_x, real vertex_1_y, real vertex_1_z, real vertex_2_x, real vertex_2_y, real vertex_2_z)
ID (-)
enve::triangleground::triangleground(integer id, real friction, point const &point_0, point const &point_1, point const &point_2)
ID (-)
enve::triangleground::triangleground(integer id, real friction, point const vertex[3])
ID (-)
void enve::triangleground::copy(triangleground const &triangleground_obj)
Input object
bool enve::triangleground::isApprox(triangleground const &triangleground_obj, real tolerance=EPSILON_LOW) const
Input object
integer const & enve::triangleground::id(void) const
Get ID const reference (-)
real const & enve::triangleground::friction(void) const
Get friction coefficent scaling factor const reference (-)
Referenced by enve::ground::mesh::print.
aabb const & enve::triangleground::bbox(void) const
Get axis-aligned bounding box const reference (m)
Referenced by print.
vec3 const & enve::triangleground::normal(void) const
Get unit normal const reference (-)
Referenced by print, enve::ground::mesh::print.
point const & enve::triangleground::operator[](size_t i) const
Index
point const & enve::triangleground::vertex(size_t i) const
Index
Referenced by print, updateBbox.
void enve::triangleground::print(out_stream &os) const
Output stream
void enve::triangleground::updateNormal(void)
Update unit normal vector with positive z-axis component.
Referenced by triangleground.
void enve::triangleground::updateBbox(void)
Update axis-aligned bounding box.
Referenced by triangleground.
point & enve::triangleground::operator[](size_t i)
Index
point & enve::triangleground::vertex(size_t i)
Index