enve::rib
typedef std::shared_ptr<rib const> enve::rib::ptr
Pointer to rib object.
typedef std::vector<rib::ptr> enve::rib::vecptr
Vector of pointers to rib objects.
real enve::rib::m_width
Rib width (m)
Referenced by copy, isApprox, operator=, width.
real enve::rib::m_angle
Rib inclination angle (rad)
Referenced by angle, copy, isApprox, operator=.
enve::rib::~rib(void)
Rib class destructor.
enve::rib::rib(rib const &)=default
Rib copy constructor.
enve::rib::rib(rib &&)=default
Rib move constructor.
enve::rib::rib(void)
Rib class constructor.
enve::rib::rib(real radius, plane const &plane, real width, real angle)
Input rib radius
enve::rib::rib(real radius, plane const &plane)
Input rib radius
enve::rib::rib(real radius, point const &center, vec3 const &normal, real width, real angle)
Input rib radius
enve::rib::rib(real radius, real center_x, real center_y, real center_z, real normal_x, real normal_y, real normal_z, real width, real angle)
Input rib radius
enve::rib::rib(real radius, real center_x, real center_y, real center_z, real normal_x, real normal_y, real normal_z)
Input rib radius
rib & enve::rib::operator=(rib const &rib_in)
Input rib object
void enve::rib::copy(rib const &rib_in)
Input object
real const & enve::rib::width(void) const
Get width coefficent scaling factor const reference (m)
Referenced by envelopGeometric, envelopSampling.
real const & enve::rib::angle(void) const
Get angle coefficent scaling factor const reference (rad)
real & enve::rib::width(void)
Set width coefficient scaling factor reference (m)
real & enve::rib::angle(void)
Set angle coefficient scaling factor reference (rad)
bool enve::rib::isApprox(rib const &rib_in, real tolerance=EPSILON_LOW) const
Input object
bool enve::rib::envelop(triangleground::vecptr const &localGround, affine const &affine_in, std::string const method, point &contactPoint, vec3 &contactNormal, real &contactFriction, real &contactDepth, real &contactArea, real &contactVolume) const
Local triangles candidate list
bool enve::rib::envelop(ground::flat const &localGround, affine const &affine_in, std::string const method, point &contactPoint, vec3 &contactNormal, real &contactFriction, real &contactDepth, real &contactArea, real &contactVolume) const
Local flat ground object
bool enve::rib::envelopGeometric(triangleground::vecptr const &localGround, affine const &affine_in, point &contactPoint, vec3 &contactNormal, real &contactFriction, real &contactDepth, real &contactArea, real &contactVolume) const
Local triangles candidate list
Referenced by envelop.
bool enve::rib::envelopGeometric(ground::flat const &localGround, affine const &affine_in, point &contactPoint, vec3 &contactNormal, real &contactFriction, real &contactDepth, real &contactArea, real &contactVolume) const
Local flat ground object
bool enve::rib::envelopSampling(triangleground::vecptr const &localGround, affine const &affine_in, point &contactPoint, vec3 &contactNormal, real &contactFriction, real &contactDepth, real &contactArea, real &contactVolume) const
Local triangles candidate list
Referenced by envelop.
bool enve::rib::envelopSampling(ground::flat const &localGround, affine const &affine_in, point &contactPoint, vec3 &contactNormal, real &contactFriction, real &contactDepth, real &contactArea, real &contactVolume) const
Local flat ground object
bool enve::rib::samplingLine(triangleground::vecptr const &localGround, point const &origin, vec3 const &direction, point &contactPoint, vec3 &contactNormal, real &contactFriction) const
Local triangles candidate list
Referenced by envelopSampling.
bool enve::rib::samplingLine(ground::flat const &localGround, point const &origin, vec3 const &direction, point &contactPoint, vec3 &contactNormal, real &contactFriction) const
Local flat ground object