enve::shell
typedef std::shared_ptr<shell const> enve::shell::ptr
Pointer to shell object.
typedef std::vector<shell::ptr> enve::shell::vecptr
Vector of pointers to shell objects.
affine enve::shell::m_affine
Shell reference frame (ISO)
Referenced by eulerAngles, linear, print, rotate, rotation, shell, transform, transformation, translate, translation, updateBBox, x, y, z.
std::vector<rib> enve::shell::m_ribs
Shell ribs vector.
Referenced by print, relativeAngles, resize, ribAngle, ribCenter, ribRadius, ribWidth, setup, size, updateRibsCandidates.
std::shared_ptr<shape> enve::shell::m_shape
Shell shape.
Referenced by checkWidthBound, print, resize, surfaceAngle, surfaceDerivative, surfaceMaxRadius, surfaceMaxWidth, surfaceRadius, surfaceWidth, updateBBox.
std::shared_ptr<aabb> enve::shell::m_aabb
Shell bounding aabb (must be transformed in the mesh reference frame before intersection!)
Referenced by BBox, setup, updateBBox.
std::vector<output> enve::shell::m_out
Contact parameters output vector.
Referenced by contactArea, contactDepth, contactFriction, contactNormal, contactPoint, contactPointAffine, contactVolume, resize, setup.
std::vector<triangleground::vecptr> enve::shell::m_candidates
Candidates triangle vector.
Referenced by resize, setup, updateRibsCandidates.
enve::shell::shell(shell const &)=delete
Shell copy constructor.
enve::shell::shell(shell &&)=delete
Shell move constructor.
shell & enve::shell::operator=(const shell &)=delete
Shell assignment operator
shell & enve::shell::operator=(shell &&)=delete
Shell move assignment operator
enve::shell::~shell(void)=default
Shell class destructor.
enve::shell::shell(size_t size, real r_x, real m_x, real r_y, real m_y, real l_y)
Input ribs number
enve::shell::shell(size_t size, shape const &shape_obj)
Input ribs number
void enve::shell::resize(size_t size)
Input ribs number
Referenced by shell.
size_t enve::shell::size(void) const
Get shell ribs number.
Referenced by contactArea, contactDepth, contactFriction, contactNormal, contactPoint, contactPointAffine, contactVolume, print, relativeAngles, resize, setup, updateRibsCandidates.
real enve::shell::surfaceMaxRadius(void) const
Get shell surface maximum radius (m)
real enve::shell::surfaceMaxWidth(void) const
Get shell surface maximum width on y axis (m)
real enve::shell::surfaceWidth(void) const
Get shell surface width (m)
bool enve::shell::checkWidthBound(real y) const
Coordinate of y axis
real enve::shell::surfaceRadius(real y) const
Coordinate of y axis
real enve::shell::surfaceDerivative(real y, real tolerance=EPSILON_MEDIUM) const
Coordinate of y axis
real enve::shell::surfaceAngle(real y, real tolerance=EPSILON_MEDIUM) const
Coordinate of y axis
real enve::shell::ribRadius(size_t i) const
Input index
point enve::shell::ribCenter(size_t i) const
Input index
real enve::shell::ribWidth(size_t i) const
Input index
real enve::shell::ribAngle(size_t i) const
Input index
void enve::shell::translate(vec3 const &vector)
Translation vector
vec3 enve::shell::translation(void) const
Returns shell translation vector.
Referenced by updateRibsCandidates.
void enve::shell::rotate(real angle, vec3 const &axis)
Input angle (rad)
void enve::shell::rotate(real angle, std::string const &axis)
Input angle (rad)
mat3 enve::shell::rotation(void) const
Returns shell rotation matrix.
Referenced by relativeAngles.
mat3 enve::shell::linear(void) const
Returns shell linear matrix (rotation + scaling + shearing)
void enve::shell::transform(affine const &pose)
Input 4x4 affine transformation matrix
Set 4x4 affine transformation matrix Warning: Rotation matrix must be orthonormal!
Referenced by setup.
void enve::shell::transform(mat4 const &pose)
Input 4x4 affine transformation matrix
Set 4x4 affine transformation matrix Warning: Rotation matrix must be orthonormal!
affine const & enve::shell::transformation(void) const
Get 4x4 affine transformation matrix.
bool enve::shell::checkTransformation(mat4 const &pose, real tolerance=EPSILON_LOW) const
Input 4x4 affine transformation matrix
Referenced by checkTransformation, transform.
bool enve::shell::checkTransformation(affine const &pose, real tolerance=EPSILON_LOW) const
Input 4x4 affine transformation matrix
vec3 enve::shell::x(void) const
Get x vector.
vec3 enve::shell::y(void) const
Get y vector.
Referenced by contactPointAffine, updateRibsCandidates.
vec3 enve::shell::z(void) const
Get z vector.
void enve::shell::eulerAngles(vec3 &angles) const
Frame Euler angles
Get current Euler angles (rad) WARNING: Rotation sequence ZXY!
Referenced by print.
std::shared_ptr< aabb > enve::shell::BBox(void) const
Get shell bonding aabb as object pointer vector.
void enve::shell::updateBBox(void)
Update shell bonding aabb.
Referenced by resize, setup, shell.
bool enve::shell::setup(ground::mesh const &ground, affine const &pose, std::string const method)
Mesh ground object
bool enve::shell::setup(ground::flat const &ground, affine const &pose, std::string const method)
Flat ground object
void enve::shell::contactPoint(point &point) const
Contact point
Referenced by contactPointAffine, print.
void enve::shell::contactPoint(size_t i, point &point) const
Input i-th index
void enve::shell::contactPoint(std::vector< point > &point) const
Contact points vector
void enve::shell::contactNormal(vec3 &normal) const
Contact point normal direction
Referenced by contactPointAffine, print.
void enve::shell::contactNormal(size_t i, vec3 &normal) const
Input i-th index
void enve::shell::contactNormal(std::vector< vec3 > &normal) const
Contact point normal direction vector
void enve::shell::contactFriction(real &friction) const
Contact friction coefficient
Referenced by print.
void enve::shell::contactFriction(size_t i, real &friction) const
Input i-th index
void enve::shell::contactFriction(std::vector< real > &friction) const
Contact friction coefficient vector
void enve::shell::contactDepth(real &depth) const
Contact depth
Referenced by print.
void enve::shell::contactDepth(size_t i, real &depth) const
Input i-th index
void enve::shell::contactDepth(std::vector< real > &depth) const
Contact depth
void enve::shell::contactArea(real &area) const
Contact area
Referenced by print.
void enve::shell::contactArea(size_t i, real &area) const
Input i-th index
void enve::shell::contactArea(std::vector< real > &area) const
Contact area vector
void enve::shell::contactVolume(real &volume) const
Contact volume
Referenced by contactDepth, contactFriction, contactNormal, contactPoint, print.
void enve::shell::contactVolume(size_t i, real &volume) const
Input i-th index
void enve::shell::contactVolume(std::vector< real > &volume) const
Contact volume vector
void enve::shell::contactPointAffine(affine &pose) const
Contact point affine transformation matrix
Referenced by contactPointAffine, print, relativeAngles.
void enve::shell::contactPointAffine(size_t i, affine &pose) const
Input i-th index
void enve::shell::contactPointAffine(std::vector< affine > &pose) const
Contact point affine transformation matrices vector
void enve::shell::relativeAngles(vec3 &angles) const
Relative angles vector (rad)
Get shell relative angles (rad) WARNING: Rotation sequence ZXY!
Referenced by print, relativeAngles.
void enve::shell::relativeAngles(size_t i, vec3 &angles) const
Input i-th index
Get shell relative angles for the i-th rib (rad) WARNING: Rotation sequence ZXY!
void enve::shell::relativeAngles(std::vector< vec3 > &angles) const
Relative angles vector (rad)
Get shell relative angles as vector (rad) WARNING: Rotation sequence ZXY!
void enve::shell::print(out_stream &os) const
Output stream type
void enve::shell::updateRibsCandidates(triangleground::vecptr const &local_ground)
Local triangles candidate list
Referenced by setup.