enve::ground::mesh
typedef std::shared_ptr<mesh const> enve::ground::mesh::ptr
Pointer to mesh object.
typedef std::vector<mesh::ptr> enve::ground::mesh::vecptr
Vector of pointers to mesh objects.
triangleground::vecptr enve::ground::mesh::m_triangles
Ground triangles pointer vector.
Referenced by copy, load, mesh, print, ptrTriangleground, size, updateBBoxes, vecptrTriangleground.
aabb::vecptr enve::ground::mesh::m_bboxes
Bounding boxes pointers vector.
Referenced by bboxes, clear, copy, load, mesh, updateBBoxes.
AABBtree::ptr enve::ground::mesh::m_AABBtree
Mesh tree pointer.
Referenced by copy, intersection, load, mesh, ptrAABBtree.
enve::ground::mesh::mesh(mesh const &)=delete
Mesh copy constructor.
enve::ground::mesh::mesh(mesh &&)=delete
Mesh move constructor.
mesh & enve::ground::mesh::operator=(const mesh &)=delete
Mesh assignment operator
mesh & enve::ground::mesh::operator=(mesh &&)=delete
Mesh move assignment operator
enve::ground::mesh::~mesh(void)=default
Mesh class destructor.
enve::ground::mesh::mesh(void)
Mesh class constructor.
enve::ground::mesh::mesh(triangleground::vecptr const &triangles)
Ground triangles pointer vector list
enve::ground::mesh::mesh(std::string const &path)
Path to the RDF file
enve::ground::mesh::mesh(std::string const &path, real friction)
Path to the OBJ file
void enve::ground::mesh::copy(mesh const &mesh_obj)
Mesh object to be copied
void enve::ground::mesh::clear(void)
Clear all mesh object data.
triangleground::vecptr const & enve::ground::mesh::vecptrTriangleground(void) const
Get all triangleground pointers inside the mesh as a vector.
triangleground::ptr enve::ground::mesh::ptrTriangleground(size_t i) const
Triangle index
Referenced by intersection.
AABBtree::ptr const enve::ground::mesh::ptrAABBtree(void) const
Get AABBtree object.
Referenced by intersection.
void enve::ground::mesh::print(std::string const &path) const
File name in which print data
aabb::vecptr const & enve::ground::mesh::bboxes(void) const
Get the mesh bounding boxes pointers vector.
size_t enve::ground::mesh::size(void) const
Return number of triangles in the mesh.
Referenced by clear.
bool enve::ground::mesh::load(std::string const &path)
Path to the file
Referenced by mesh.
bool enve::ground::mesh::load(std::string const &path, real friction)
Path to the file
bool enve::ground::mesh::intersection(AABBtree::ptr const AABBtree, triangleground::vecptr &triangles) const
External AABBtree object pointer
Referenced by intersection, enve::shell::setup.
bool enve::ground::mesh::intersection(aabb::vecptr const &boxes, triangleground::vecptr &triangles) const
External aabb object pointer vector
bool enve::ground::mesh::intersection(aabb::ptr const box, triangleground::vecptr &triangles) const
External aabb object pointer
void enve::ground::mesh::updateBBoxes(void)
Update the mesh bounding boxes pointers.
Referenced by load, mesh.
void enve::ground::mesh::split(std::string const &in, std::vector< std::string > &out, std::string const &token) const
Input string
Referenced by load.
std::string enve::ground::mesh::tail(std::string const &in) const
Input string
Referenced by load.
std::string enve::ground::mesh::firstToken(std::string const &in) const
Input string
Referenced by load.