enve::points
typedef std::shared_ptr<points const> enve::points::ptr
Pointer to points object.
typedef std::vector<points::ptr> enve::points::vecptr
Vector of pointers to points objects.
vecN enve::points::m_dataR
Vector of radius data (m)
Referenced by copy, dataR, isApprox, print, surfaceDerivative, surfaceRadius.
vecN enve::points::m_dataY
Vector of y data (m)
Referenced by copy, dataY, isApprox, lowerBound, print, size, surfaceDerivative, surfaceRadius, upperBound.
real enve::shape::m_maxR
Maximum surface maximum radius (m)
Referenced by enve::shape::copy, enve::shape::isApprox, enve::shape::print, enve::shape::shape, enve::shape::surfaceMaxRadius.
real enve::shape::m_minY
Minimum surface bound on y axis (m)
Referenced by enve::shape::checkWidthBound, enve::shape::copy, enve::shape::isApprox, enve::shape::print, enve::shape::shape, enve::shape::surfaceMaxWidth, enve::shape::surfaceWidth, enve::shape::surfaceWidthLowerBound.
real enve::shape::m_maxY
Maximum surface bound on y axis (m)
Referenced by enve::shape::checkWidthBound, enve::shape::copy, enve::shape::isApprox, enve::shape::print, enve::shape::shape, enve::shape::surfaceMaxWidth, enve::shape::surfaceWidth, enve::shape::surfaceWidthUpperBound.
enve::points::~points(void)
Polynom class destructor.
enve::points::points(points const &)=default
Polynom copy constructor.
enve::points::points(points &&)=default
Polynom move constructor.
enve::points::points(void)
Polynom class constructor.
enve::points::points(vecN const &dataR, vecN const &dataY)
Vector of radius data (m)
void enve::points::copy(points const &points_in)
Polynom object to be copied
bool enve::points::isApprox(points const &points_in, real tolerance=EPSILON_LOW) const
Input object
vecN const & enve::points::dataR(void) const
Get radius vector const reference (m)
real const & enve::points::dataR(size_t i) const
Input i-th index
vecN const & enve::points::dataY(void) const
Get width vector const reference (m)
real const & enve::points::dataY(size_t i) const
Input i-th index
vecN & enve::points::dataR(void)
Get radius vector reference (m)
real & enve::points::dataR(size_t i)
Input i-th index
vecN & enve::points::dataY(void)
Get width vector reference (m)
real & enve::points::dataY(size_t i)
Input i-th index
size_t enve::points::size(void) const
Get data vector size (m)
size_t enve::points::lowerBound(real y) const
Coordinate of y axis
Referenced by surfaceDerivative, surfaceRadius.
size_t enve::points::upperBound(real y) const
Coordinate of y axis
Referenced by surfaceDerivative.
real enve::points::surfaceRadius(real y) const override
Coordinate of y axis
real enve::points::surfaceDerivative(real y, real tolerance=EPSILON_MEDIUM) const override
Coordinate of y axis
Referenced by surfaceAngle, surfaceRadius.
real enve::points::surfaceAngle(real y, real tolerance=EPSILON_MEDIUM) const override
Coordinate of y axis
void enve::points::print(out_stream &os) const
Output stream type
void enve::shape::copy(shape const &shape_in)
Shape object to be copied
Referenced by enve::hyperellipse::copy, copy, enve::polynom::copy.
bool enve::shape::isApprox(shape const &shape_in, real tolerance=EPSILON_LOW) const
Shape object
Referenced by enve::hyperellipse::isApprox, isApprox, enve::polynom::isApprox.
real const & enve::shape::surfaceMaxRadius(void) const
Get surface maximum radius const reference (m)
Referenced by enve::hyperellipse::updateBounds.
real & enve::shape::surfaceMaxRadius(void)
Get surface maximum radius on reference (m)
real enve::shape::surfaceMaxWidth(void) const
Get surface maximum width on y axis (m)
real const & enve::shape::surfaceWidthLowerBound(void) const
Get surface minimum width const reference (m)
Referenced by enve::hyperellipse::updateBounds.
real & enve::shape::surfaceWidthLowerBound(void)
Get surface minimum width on reference (m)
real const & enve::shape::surfaceWidthUpperBound(void) const
Get surface maximum width const reference (m)
Referenced by enve::hyperellipse::updateBounds.
real & enve::shape::surfaceWidthUpperBound(void)
Get surface maximum width on reference (m)
real enve::shape::surfaceWidth(void) const
Get surface width (m)
bool enve::shape::checkWidthBound(real y) const
Coordinate of y axis
Referenced by lowerBound, enve::hyperellipse::surfaceDerivative, surfaceDerivative, enve::polynom::surfaceDerivative, enve::hyperellipse::surfaceRadius, surfaceRadius, enve::polynom::surfaceRadius, upperBound.